baseURL = "https://www.tio.moe"

# [en, zh-cn, fr, pl, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"

# 主题
theme = "LoveIt"

# 主题目录
#themesDir = "../.."

# 网站标题
title = "Tio's Blog"

# 是否使用 robots.txt
enableRobotsTXT = true

# 是否使用 git 信息
enableGitInfo = true

# 是否使用 emoji 代码
enableEmoji = true

[languages]
#TAG:zh-cn
[languages.zh-cn]
weight = 1
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
# 语言名称
languageName = "简体中文"
# 是否包括中日韩文字
hasCJKLanguage = true
# 版权描述，仅仅用于 SEO
copyright = "本作品采用知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议进行许可。"

#TAG zh-cn.menu
[languages.zh-cn.menu]
[[languages.zh-cn.menu.main]]
identifier = "posts"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ""
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
name = "文章"
post = ""
title = ""
url = "/posts/"
weight = 1
[[languages.zh-cn.menu.main]]
identifier = "tags"
name = "标签"
post = ""
pre = ""
title = ""
url = "/tags/"
weight = 2
[[languages.zh-cn.menu.main]]
identifier = "categories"
name = "分类"
post = ""
pre = ""
title = ""
url = "/categories/"
weight = 3
[[languages.zh-cn.menu.main]]
identifier = "documentation"
name = "文档"
pre = ""
title = ""
url = "/categories/documentation/"
weight = 4
[[languages.zh-cn.menu.main]]
identifier = "about"
name = "关于"
post = ""
pre = ""
title = ""
url = "/about/"
weight = 5
[[languages.zh-cn.menu.main]]
identifier = "github"
name = ""
post = ""
pre = "<i class='fab fa-github fa-fw'></i>"
title = "GitHub"
url = "https://github.com/TioPIato/blog"
weight = 6

[languages.zh-cn.params]
# 网站描述
description = "Tio的博客"

#TAG zh-cn 应用图标
[languages.zh-cn.params.app]
# 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
title = "Tio的博客"
# 是否隐藏网站图标资源链接
noFavicon = false
# 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
svgFavicon = ""
# Android 浏览器主题色
themeColor = "#ffffff"
# Safari 图标颜色
iconColor = "#5bbad5"
# Windows v8-10 磁贴颜色
tileColor = "#da532c"

#TAG zh-cn 搜索
[languages.zh-cn.params.search]
enable = true
# 搜索引擎的类型 ("lunr", "algolia")
type = "lunr"
# 文章内容最长索引长度
contentLength = 4000
# 搜索框的占位提示语
placeholder = ""
# 最大结果数目
maxResultLength = 10
# 结果内容片段长度
snippetLength = 50
# 搜索结果中高亮部分的 HTML 标签
highlightTag = "em"
# 是否在搜索索引中使用基于 baseURL 的绝对路径
absoluteURL = false
[languages.zh-cn.params.search.algolia]
index = "index.zh-cn"
appID = "PASDMWALPK"
searchKey = "b42948e51daaa93df92381c8e2ac0f93"


#TAG zh-cn 页面头部
[languages.zh-cn.params.header]
# 桌面端导航栏模式 ("fixed", "normal", "auto")
desktopMode = "normal"
# 移动端导航栏模式 ("fixed", "normal", "auto")
mobileMode = "auto"

# 页面头部导航栏标题配置
[languages.zh-cn.params.header.title]
# LOGO 的 URL
logo = ""
# title name
# 标题名称
name = "Tio的博客"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = "<i class='fas fa-chevron-right fa-fw'></i>"
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
# 是否为标题显示打字机动画
typeit = true

#TAG zh-cn 页面底部
[languages.zh-cn.params.footer]
enable = true
# 自定义内容 (支持 HTML 格式)
custom = ''
# 是否显示 Hugo 和主题信息
hugo = false
# 是否显示版权信息
copyright = true
# 是否显示作者
author = true
# 网站创立年份
since = 2020
# ICP 备案信息，仅在中国使用 (支持 HTML 格式)
icp = ""
# 许可协议信息 (支持 HTML 格式)
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc-nd/4.0/deed.zh" target="_blank">CC BY-NC-ND 4.0</a>'

#TAG zh-cn 主页
[languages.zh-cn.params.home]
# RSS 文章数目
rss = 10

[languages.zh-cn.params.home.posts]
# 主页是否显示文章
enable = true
# 主页每页显示文章数量
paginate = 6

# 主页个人信息
[languages.zh-cn.params.home.profile]
enable = true
# Gravatar 邮箱，用于优先在主页显示的头像
gravatarEmail = ""
# 主页显示头像的 URL
avatarURL = "/images/avatar.png"
# 主页显示的网站标题 (支持 HTML 格式)
title = ""
# 主页显示的网站副标题
subtitle = "施工中……"
# 是否为副标题显示打字机动画
typeit = true
# 是否显示社交账号
social = true
# 免责声明 (支持 HTML 格式)
disclaimer = ""

#TAG:en
[languages.en]
weight = 2
# language code
languageCode = "en"
# language name
languageName = "English"
# whether to include Chinese/Japanese/Korean
hasCJKLanguage = false
# copyright description used only for seo schema
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License."
#TAG en.menu

# Menu config
[languages.en.menu]
[[languages.en.menu.main]]
identifier = "posts"
# you can add extra information before the name (HTML format is supported), such as icons
pre = ""
# you can add extra information after the name (HTML format is supported), such as icons
name = "Posts"
post = ""
url = "/posts/"
# title will be shown when you hover on this menu link.
title = ""
weight = 1
[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
post = ""
pre = ""
title = ""
url = "/tags/"
weight = 2
[[languages.en.menu.main]]
identifier = "categories"
name = "Categories"
post = ""
pre = ""
title = ""
url = "/categories/"
weight = 3
[[languages.en.menu.main]]
identifier = "documentation"
name = "Docs"
post = ""
pre = ""
title = ""
url = "/categories/documentation/"
weight = 4
[[languages.en.menu.main]]
identifier = "about"
name = "About"
post = ""
pre = ""
title = ""
url = "/about/"
weight = 5
[[languages.en.menu.main]]
identifier = "github"
name = ""
post = ""
pre = "<i class='fab fa-github fa-fw'></i>"
title = "GitHub"
url = "https://github.com/TioPIato/blog"
weight = 6

[languages.en.params]
# site description
description = "Tio's Blog"

#TAG en 应用图标
[languages.en.params.app]
# optional site title override for the app when added to an iOS home screen or Android launcher
title = "Tio's Blog"
# 是否隐藏网站图标资源链接
noFavicon = false
# 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
svgFavicon = ""
# Android 浏览器主题色
themeColor = "#ffffff"
# Safari 图标颜色
iconColor = "#5bbad5"
# Windows v8-10 磁贴颜色
tileColor = "#da532c"


#TAG en 搜索
[languages.en.params.search]
enable = true
# 搜索引擎的类型 ("lunr", "algolia")
type = "lunr"
# 文章内容最长索引长度
contentLength = 4000
# 搜索框的占位提示语
placeholder = ""
# 最大结果数目
maxResultLength = 10
# 结果内容片段长度
snippetLength = 50
# 搜索结果中高亮部分的 HTML 标签
highlightTag = "em"
# 是否在搜索索引中使用基于 baseURL 的绝对路径
absoluteURL = false
[languages.en.params.search.algolia]
index = "index.en"
appID = "PASDMWALPK"
searchKey = "b42948e51daaa93df92381c8e2ac0f93"

#TAG en 页面头部
[languages.en.params.header]
# 桌面端导航栏模式 ("fixed", "normal", "auto")
desktopMode = "normal"
# 移动端导航栏模式 ("fixed", "normal", "auto")
mobileMode = "auto"

# 页面头部导航栏标题配置
[languages.en.params.header.title]
# LOGO 的 URL
logo = ""
# title name
# 标题名称
name = "Tio's Blog"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = "<i class='fas fa-chevron-right fa-fw'></i>"
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
# 是否为标题显示打字机动画
typeit = true

#TAG en 页面底部
[languages.en.params.footer]
enable = true
# 自定义内容 (支持 HTML 格式)
custom = ''
# 是否显示 Hugo 和主题信息
hugo = false
# 是否显示版权信息
copyright = true
# 是否显示作者
author = true
# 网站创立年份
since = 2020
# ICP 备案信息，仅在中国使用 (支持 HTML 格式)
icp = ""
# 许可协议信息 (支持 HTML 格式)
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

#TAG en 主页
[languages.en.params.home]
# RSS 文章数目
rss = 10

[languages.en.params.home.posts]
# 主页是否显示文章
enable = true
# 主页每页显示文章数量
paginate = 6

# Home page profile
[languages.en.params.home.profile]
enable = true
# Gravatar Email for preferred avatar in home page
gravatarEmail = ""
# URL of avatar shown in home page
avatarURL = "/images/avatar.png"
# title shown in home page (HTML format is supported)
title = ""
# subtitle shown in home page
subtitle = "Under construction..."
# whether to use typeit animation for subtitle
typeit = true
# whether to show social links
social = true
# disclaimer (HTML format is supported)
disclaimer = ""

#TAG:fr
[languages.fr]
weight = 3
# language code
languageCode = "fr"
# language name
languageName = "Français"
# whether to include Chinese/Japanese/Korean
hasCJKLanguage = false
# copyright description used only for seo schema
copyright = "Ce(tte) œuvre est mise à disposition selon les termes de la Licence Creative Commons Attribution - Pas d'Utilisation Commerciale - Pas de Modification 4.0 International."

#TAG fr.menu
# Menu config
[languages.fr.menu]
[[languages.fr.menu.main]]
identifier = "posts"
name = "Postes"
post = ""
pre = ""
title = ""
url = "/posts/"
weight = 1
[[languages.fr.menu.main]]
identifier = "tags"
name = "Balises"
post = ""
pre = ""
title = ""
url = "/tags/"
weight = 2
[[languages.fr.menu.main]]
identifier = "categories"
name = "Catégories"
post = ""
pre = ""
title = ""
url = "/categories/"
weight = 3
[[languages.fr.menu.main]]
identifier = "documentation"
name = "Docs"
post = ""
pre = ""
title = ""
url = "/categories/documentation/"
weight = 4
[[languages.fr.menu.main]]
identifier = "about"
name = "À propos"
pre = ""
title = ""
url = "/about/"
weight = 5
[[languages.fr.menu.main]]
identifier = "github"
name = ""
post = ""
pre = "<i class='fab fa-github fa-fw'></i>"
title = "GitHub"
url = "https://github.com/TioPIato/blog"
weight = 6

[languages.fr.params]
# site description
description = "Blog de Tio"

#TAG fr 应用图标
[languages.fr.params.app]
# optional site title override for the app when added to an iOS home screen or Android launcher
title = "Blog de Tio"
# 是否隐藏网站图标资源链接
noFavicon = false
# 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
svgFavicon = ""
# Android 浏览器主题色
themeColor = "#ffffff"
# Safari 图标颜色
iconColor = "#5bbad5"
# Windows v8-10 磁贴颜色
tileColor = "#da532c"

#TAG fr 搜索
[languages.fr.params.search]
enable = true
# 搜索引擎的类型 ("lunr", "algolia")
type = "lunr"
# 文章内容最长索引长度
contentLength = 4000
# 搜索框的占位提示语
placeholder = ""
# 最大结果数目
maxResultLength = 10
# 结果内容片段长度
snippetLength = 50
# 搜索结果中高亮部分的 HTML 标签
highlightTag = "em"
# 是否在搜索索引中使用基于 baseURL 的绝对路径
absoluteURL = false
[languages.fr.params.search.algolia]
index = "index.fr"
appID = "PASDMWALPK"
searchKey = "b42948e51daaa93df92381c8e2ac0f93"

#TAG fr 页面头部
[languages.fr.params.header]
# 桌面端导航栏模式 ("fixed", "normal", "auto")
desktopMode = "normal"
# 移动端导航栏模式 ("fixed", "normal", "auto")
mobileMode = "auto"

# 页面头部导航栏标题配置
[languages.fr.params.header.title]
# LOGO 的 URL
logo = ""
# title name
# 标题名称
name = "Blog de Tio"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = "<i class='fas fa-chevron-right fa-fw'></i>"
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
# 是否为标题显示打字机动画
typeit = true

##TAG fr 页面底部信息
[languages.fr.params.footer]
enable = true
# 自定义内容 (支持 HTML 格式)
custom = ''
# 是否显示 Hugo 和主题信息
hugo = false
# 是否显示版权信息
copyright = true
# 是否显示作者
author = true
# 网站创立年份
since = 2020
# ICP 备案信息，仅在中国使用 (支持 HTML 格式)
icp = ""
# 许可协议信息 (支持 HTML 格式)
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc-nd/4.0/deed.fr" target="_blank">CC BY-NC-ND 4.0</a>'

#TAG fr 主页
[languages.fr.params.home]
# RSS 文章数目
rss = 10

[languages.fr.params.home.posts]
# 主页是否显示文章
enable = true
# 主页每页显示文章数量
paginate = 6

# Home page profile
[languages.fr.params.home.profile]
enable = true
# Gravatar Email for preferred avatar in home page
gravatarEmail = ""
# URL of avatar shown in home page
avatarURL = "/images/avatar.png"
# title shown in home page (HTML format is supported)
title = ""
# subtitle shown in home page
subtitle = "En construction..."
# whether to use typeit animation for subtitle
typeit = true
# whether to show social links
social = true
# disclaimer (HTML format is supported)
disclaimer = ""

#TAG params
[params]
# LoveIt theme version
# LoveIt 主题版本
version = "0.2.X"
# site default theme ("light", "dark", "auto")
# 网站默认主题 ("light", "dark", "auto")
defaultTheme = "auto"
# public git repo url only then enableGitInfo is true
# 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
gitRepo = "https://github.com/TioPIato/blog.git"
# which hash function used for SRI, when empty, no SRI is used ("sha256", "sha384", "sha512", "md5")
# 哪种哈希函数用来 SRI, 为空时表示不使用 SRI ("sha256", "sha384", "sha512", "md5")
fingerprint = ""
# date format
# 日期格式
dateFormat = "2006.1.2"
# website images for Open Graph and Twitter Cards
# 网站图片, 用于 Open Graph 和 Twitter Cards
images = ["/logo.png"]
# 网站关键词
keywords = []

#TAG 主页社交信息
[params.social]
Angellist = ""
Bandcamp = ""
Behance = ""
Bilibili = ""
Bitbucket = ""
Codepen = ""
Deviantart = ""
Devto = ""
Douban = ""
Dribbble = ""
Email = "xxxx@xxxx.com"
Facebook = ""
Fivehundredpx = ""
Flickr = ""
Foursquare = ""
FreeCodeCamp = ""
GitHub = ""
Gitea = ""
Gitlab = ""
Goodreads = ""
Googlescholar = ""
Hackernews = ""
Instagram = ""
Jsfiddle = ""
Keybase = ""
Kickstarter = ""
Lastfm = ""
Linkedin = ""
Mastodon = ""
Matrix = ""
Medium = ""
Mix = ""
Odnoklassniki = ""
Patreon = ""
Paypal = ""
Pinterest = ""
Quora = ""
RSS = true
Reddit = ""
Researchgate = ""
Skype = ""
Slidershare = ""
Snapchat = ""
Soundcloud = ""
Spotify = ""
Stackoverflow = ""
Steam = ""
Strava = ""
Telegram = ""
Thingiverse = ""
Tumblr = ""
Twitch = ""
Twitter = ""
VK = ""
Vine = ""
Weibo = ""
Whatsapp = ""
Wordpress = ""
XMPP = ""
Xing = ""
Youtubechannel = ""
Youtubecustom = ""
Youtubelegacy = ""
Zhihu = ""

#TAG Section (所有文章) 页面配置
[params.section]
# section 页面每页显示文章数量
paginate = 20
# 日期格式 (月和日)
dateFormat = "1.2"
# RSS 文章数目
rss = 10

#TAG List (目录或标签) 页面配置
[params.list]
# list 页面每页显示文章数量
paginate = 20
# 日期格式 (月和日)
dateFormat = "1.2"
# RSS 文章数目
rss = 10

#TAG 文章页面配置
[params.page]
# 是否在主页隐藏一篇文章
hiddenFromHomePage = false
# 是否在搜索结果中隐藏一篇文章
hiddenFromSearch = false
# 是否使用 twemoji
twemoji = false
# 是否使用 lightgallery
lightgallery = false
# 是否使用 ruby 扩展语法
ruby = true
# 是否使用 fraction 扩展语法
fraction = true
# 是否使用 fontawesome 扩展语法
fontawesome = true
# 是否显示原始 Markdown 文档内容的链接
linkToMarkdown = true
# 是否在 RSS 中显示全文内容
rssFullText = false

#TAG 目录配置
[params.page.toc]
# 是否使用目录
enable = true
# 是否保持使用文章前面的静态目录
keepStatic = false
# 是否使侧边目录自动折叠展开
auto = false

#TAG 代码配置
[params.page.code]
# 是否显示代码块的复制按钮
copy = true
# 默认展开显示的代码行数
maxShownLines = 10

#TAG KaTeX 数学公式配置 (KaTeX https://katex.org/)
[params.page.math]
enable = true
# 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
blockLeftDelimiter = ""
blockRightDelimiter = ""
# 默认行内定界符是 $ ... $ 和 \\( ... \\)
inlineLeftDelimiter = ""
inlineRightDelimiter = ""
# KaTeX 插件 copy_tex
copyTex = true
# KaTeX 插件 mhchem
mhchem = true

#TAG Mapbox GL JS 配置 (Mapbox GL JS https://docs.mapbox.com/mapbox-gl-js)
[params.page.mapbox]
# Mapbox GL JS 的 access token
accessToken = "pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ"
# 浅色主题的地图样式
lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
# 深色主题的地图样式
darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
# 是否添加 NavigationControl (https://docs.mapbox.com/mapbox-gl-js/api/#navigationcontrol)
navigation = true
# 是否添加 GeolocateControl (https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol)
geolocate = true
# 是否添加 ScaleControl (https://docs.mapbox.com/mapbox-gl-js/api/#scalecontrol)
scale = true
# 是否添加 FullscreenControl (https://docs.mapbox.com/mapbox-gl-js/api/#fullscreencontrol)
fullscreen = true

#TAG 文章页面的分享信息设置
[params.page.share]
Baidu = false
Blogger = false
Buffer = false
Digg = false
Evernote = true
Facebook = true
Flipboard = false
HackerNews = false
Instapaper = false
Line = true
Linkedin = false
Mix = false
Myspace = false
Odnoklassniki = false
Pinterest = false
Pocket = true
Reddit = true
Renren = false
Skype = false
Stumbleupon = false
Trello = false
Tumblr = false
Twitter = true
VK = false
Weibo = true
Whatsapp = false
Xing = false
enable = true

#TAG 评论系统设置
[params.page.comment]
enable = true

# Disqus 评论系统设置 (https://disqus.com/)
[params.page.comment.disqus]
enable = false
# Disqus 的 shortname，用来在文章中启用 Disqus 评论系统
shortname = ""

# Gitalk 评论系统设置 (https://github.com/gitalk/gitalk)
[params.page.comment.gitalk]
clientId = ""
clientSecret = ""
enable = false
owner = ""
repo = ""

# Valine 评论系统设置 (https://github.com/xCss/Valine)
[params.page.comment.valine]
appId = "zbOFnJ4G5hSt32xmKmdEgo6o-MdYXbMMI"
appKey = "hvh9mvAEw8BLRqU7YpMVpsCx"
# https://valine.js.org/avatar.html
avatar = "mp"
enable = true
enableQQ = false
highlight = true
lang = ""
meta = ""
pageSize = 10
# 评论框提示占位符
placeholder = ""
recordIP = true
serverURLs = ""
visitor = true
# emoji 数据文件名称, 默认是 "google.yml"
# ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
# 位于 "themes/LoveIt/assets/data/emoji/" 目录
# 可以在你的项目下相同路径存放你自己的数据文件:
# "assets/data/emoji/"
emoji = ""

# Facebook 评论系统设置 (https://developers.facebook.com/docs/plugins/comments)
[params.page.comment.facebook]
appId = ""
enable = false
languageCode = ""
numPosts = 10
width = "100%"

# Telegram comments 评论系统设置 (https://comments.app/)
[params.page.comment.telegram]
color = ""
colorful = true
dislikes = false
enable = false
height = ""
limit = 5
outlined = false
siteID = ""

# Commento comment 评论系统设置 (https://commento.io/)
[params.page.comment.commento]
enable = false

# Utterances comment 评论系统设置 (https://utteranc.es/)
[params.page.comment.utterances]
enable = false
# owner/repo
darkTheme = "github-dark"
issueTerm = "pathname"
label = ""
lightTheme = "github-light"
repo = ""

#TAG 第三方库配置
[params.page.library]
[params.page.library.css]
# someCSS = "some.css"
# 位于 "assets/"
# 或者
# someCSS = "https://cdn.example.com/some.css"
[params.page.library.js]
# someJavascript = "some.js"
# 位于 "assets/"
# 或者
# someJavascript = "https://cdn.example.com/some.js"

# 页面 SEO 配置
[params.page.seo]
# 图片 URL
images = []

#TAG 出版者信息
[params.page.seo.publisher]
logoUrl = "/images/avatar.png"
name = "TioPlato"

#TAG TypeIt 配置
[params.typeit]
# 每一步的打字速度 (单位是毫秒)
speed = 100
# 光标的闪烁速度 (单位是毫秒)
cursorSpeed = 800
# 光标的字符 (支持 HTML 格式)
cursorChar = "|"
# 打字结束之后光标的持续时间 (单位是毫秒, "-1" 代表无限大)
duration = 1600

#TAG 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu
[params.verification]
baidu = ""
bing = ""
google = ""
pinterest = ""
yandex = ""

#TAG 网站 SEO 配置
[params.seo]
# 图片 URL
image = "/images/Apple-Devices-Preview.png"
# 缩略图 URL
thumbnailUrl = "/images/screenshot.png"

#TAG 网站分析配置
[params.analytics]
enable = true

# Google Analytics
[params.analytics.google]
id = "UA-172966803-1"
# 是否匿名化用户 IP
anonymizeIP = false

# Fathom Analytics
[params.analytics.fathom]
id = ""
# 自行托管追踪器时的主机路径
server = ""

# Cookie 许可配置
[params.cookieconsent]
enable = false
# 用于 Cookie 许可横幅的文本字符串
[params.cookieconsent.content]
dismiss = ""
link = ""
message = ""

#TAG 第三方库文件的 CDN 设置
[params.cdn]
# CDN 数据文件名称, 默认不启用
# ("jsdelivr.yml")
# 位于 "themes/LoveIt/assets/data/cdn/" 目录
# 可以在你的项目下相同路径存放你自己的数据文件:
# "assets/data/cdn/"
data = "jsdelivr.yml"

#TAG 兼容性设置
[params.compatibility]
# 是否使用 Polyfill.io 来兼容旧式浏览器
polyfill = true
# 是否使用 object-fit-images 来兼容旧式浏览器
objectFit = true

#TAG Hugo 解析文档的配置
[markup]

# 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = true
# false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false

# Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.renderer]
# 是否在文档中直接使用 HTML 标签
unsafe = true

# 目录设置
[markup.tableOfContents]
endLevel = 6
startLevel = 2

#TAG 作者配置
[author]
email = ""
link = ""
name = "TioPlato"

#TAG 网站地图配置
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

# Permalinks 配置 (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
# posts = ":year/:month/:filename"
posts = ":filename"

# 隐私信息配置 (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]

# ...
[privacy.twitter]
enableDNT = true
[privacy.youtube]
privacyEnhanced = true

# 用于输出 Markdown 格式文档的设置
[mediaTypes]
[mediaTypes."text/plain"]
suffixes = ["md"]

# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
isHTML = false
isPlainText = true
mediaType = "text/plain"

# 用于 Hugo 输出文档的设置
[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
taxonomyTerm = ["HTML"]
